### ISSUE TITLE
Consultant webpage - displaying closed parties in the 'attend' section

### ISSUE THREAD

**Issue by suehamre** [tastefully-simple/cornerstone#289]
### Expected behavior
The 'My parties' section on the consultants webpage should only display OPEN parties that have a party date within the last 30 days. This is applies to the 'Attend' and 'Past' 

### Actual behavior
The 'attend' section is displaying a closed party. 

### Steps to reproduce behavior
Closed party in myHQ. Party Details: 
![image](https://user-images.githubusercontent.com/57115316/90827655-35300280-e302-11ea-8db5-17f3465f7847.png)
When viewing the consultants webpage after closing the party it is still displayed. I have cleared cookies and waited awhile. 
Harper Test's Party with party date of 8/22 is the one closed
![image](https://user-images.githubusercontent.com/57115316/90827728-5d1f6600-e302-11ea-88e5-013e4501c894.png)

NOTE: When searching for parties by state MN and name Harper the closed party no longer appears. This is good. :)

**Comment by richierubin** [comment]
I can't duplicate this issue via API.  Within Postman, using the same consultant (0000028), I don't see any current parties.

![image](https://user-images.githubusercontent.com/66743596/92028455-b4253200-ed29-11ea-8fea-ef30d0cc2312.png)

**Comment by suehamre** [comment]
@richierubin  - This is strange, I am no longer seeing the closed party under the attend section either. However, I closed another party over a half hour ago and it is still showing under the past parties. 
The first one in this screenshot 'Jason Hamre's party' is the one I closed. 
![image](https://user-images.githubusercontent.com/57115316/92033835-f18dbd80-ed31-11ea-86c7-8742e62743d7.png)
Party ID # 

10370747
--

**Comment by richierubin** [comment]
Fixed.  

- Removed the top 3 limitation for both current and past parties.
- added logic to only pull past 30 days for past parties and not closed.
- ordered current parties by asc (closest to current date, first), and past parties by decending (most recent, first).

**Comment by suehamre** [comment]
9-4  - Reopening this bug, this is still an issue. 
Requirement: For the attend section, parties that are open and have a party date in the future or is not more than 30 days past the current date will display under 'attend' on the consultants webpage. 
Party ID#10370775 - I closed and it is still displaying under the 'attend' section and should not be because it is closed. 
![image](https://user-images.githubusercontent.com/57115316/92282071-87585280-eec2-11ea-8ed6-48b7c31481d7.png)

**Comment by suehamre** [comment]
9-4 Fixed again.:)
